---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: per-zkwasm-server
  name: per-zkwasm-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: per-zkwasm-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/name: per-zkwasm-server
    spec:
      containers:
        - env:
            - name: REDISHOST
              value: redis
            - name: URI
              value: 'mongodb://mongo:27017'
            - name: MERKLE_SERVER
              value: 'http://zkdb:3030'
            - name: DEPLOY
              value: 'true'
            - name: SETTLEMENT_CONTRACT_ADDRESS
              value: '0x85d56DA855E85154c23eBC3D9E6FcD7dB348019C'
            - name: SETTLER_PRIVATE_ACCOUNT
              value: {{SETTLER_PRIVATE_ACCOUNT}}
            - name: RPC_PROVIDER
              value: {{RPC_URL}}
          image: >-
            registry.ap-northeast-1.aliyuncs.com/omni-new/per-zkwasm-server:{{IMAGE_VERSION}}
          imagePullPolicy: IfNotPresent
          name: per-zkwasm-server
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
            - /app/ts/node_modules/zkwasm-ts-server/src/settle.js
          command:
            - node
          env:
            - name: SETTLEMENT_CONTRACT_ADDRESS
              value: '0x85d56DA855E85154c23eBC3D9E6FcD7dB348019C'
            - name: SETTLER_PRIVATE_ACCOUNT
              value: {{SETTLER_PRIVATE_ACCOUNT}}
            - name: RPC_PROVIDER
              value: {{RPC_URL}}
            - name: REDISHOST
              value: redis
            - name: URI
              value: 'mongodb://mongo:27017'
            - name: MERKLE_SERVER
              value: 'http://zkdb:3030'
            - name: DEPLOY
              value: 'true'

          image: >-
            registry.ap-northeast-1.aliyuncs.com/omni-new/per-zkwasm-server:{{IMAGE_VERSION}}
          imagePullPolicy: IfNotPresent
          name: settle
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: alihub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: per-zkwasm-server
  name: per-zkwasm-server
  namespace: default
spec:
  clusterIP: 10.43.255.146
  clusterIPs:
    - 10.43.255.146
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    k8s.kuboard.cn/name: per-zkwasm-server
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: per-zkwasm-server
  name: per-zkwasm-server
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: zk-server.pumpelf.ai
      http:
        paths:
          - backend:
              service:
                name: per-zkwasm-server
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - zk-server.pumpelf.ai
      secretName: pumpelf.ai

