pub const ERROR_PLAYER_ALREADY_EXIST: u32 = 1;
pub const ERROR_PLAYER_NOT_EXIST: u32 = 2;
pub const ERROR_NOT_GOLD_BALANCE: u32 = 3;
pub const ERROR_INDEX_OUT_OF_BOUND: u32 = 4;
pub const ERROR_NOT_ENOUGH_RESOURCE: u32 = 5;

pub const ERROR_NOT_FOUND_RANCH: u32 = 6;

pub const ERROR_MAX_ELF: u32 = 7;

pub const ERROR_INVALID_PURCHASE_CONDITION: u32 = 8;

pub const ERROR_NOT_FOUND_ELF: u32 = 9;

pub const ERROR_NOT_FOUND_PROP: u32 = 10;

pub const  ERROR_THIS_PROP_MUST_BE_USED_USDT: u32 = 11;

pub const  ERROR_MAX_ELF_SLOT: u32 = 12;